# Generated by Django 5.1.3 on 2024-12-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_remove_book_author_delete_author_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='child_event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_events', to='myapp.event'),
        ),
    ]
